### ISSUE TITLE
Defining the functionalities

### ISSUE THREAD

**Issue by Ynefota** [Ynefota/caged#1]
look at what is possible the current ideas are:
* MVC
* Routes
* Non-Blocking
* Templating
* various databases
* Simple insertion of modules
* JWT implementation
* authentication per module

**Comment by noebuerki** [comment]
Nice ideas

**Comment by Ynefota** [comment]
To begin with, I will show the structure of the framework in a class diagram. First I will introduce the basic structures and then come back to my ideas.
